### ISSUE TITLE
More simplified meshes

### ISSUE THREAD

**Issue by Morgantiz** [ADVRHumanoids/concert_resources#1]
I am working with these meshes and I am having a lot of problems with the frame rate of rviz, indeed I noticed that the meshes are very accurate.

It would be helpful to simplify them so it's possible to use even computers with less performance to work on them.

**Comment by EdoardoRomiti** [comment]
Hi @Morgantiz, yes I agree this first version of the meshes is a bit heavy. 
I guess you are mainly referring to the mobile base mesh right? 
What I can suggest if you are having issues, is to consider using the [ **"collision mesh"**](https://github.com/ADVRHumanoids/modular_resources/blob/master/models/modular/meshes/concert/simple/concert_central_body.stl) also for visualization for now.
We are anyway going to provide a simpler version in the future. 

@StecarGit whenever we reach a definitive version of the mobile base can we work to have a less detailed, slightly lighter mesh?

**Comment by Morgantiz** [comment]
Thanks, using collision meshes in the visualization the fps of rviz are better

**Comment by EdoardoRomiti** [comment]
Hi @Morgantiz , we have updated the mesh of the `concert_central_body` to be lighter. I guess this should improve performance for less performant PCs, can you give it a try when you have some free time?
If it's better you can stop using the collision mesh also for visualization and close this issue

**Comment by Morgantiz** [comment]
The problems seem to have disappeared and performance improved
