### ISSUE TITLE
Dev branch creation

### ISSUE THREAD

**Issue by TUM-CPS-CONCERT** [ADVRHumanoids/concert_resources#2]
Hi @EdoardoRomiti,

Could you add us to be able to push dev branches with some alterations that might accumulate over the integration meeting?

-- Matthias

**Comment by TUM-CPS-CONCERT** [comment]
(for now forked at https://github.com/TUM-CPS-CONCERT/concert_resources/tree/dev/integration)

**Comment by EdoardoRomiti** [comment]
Hi, I've added the @ADVRHumanoids/concert team (and therefore also @TUM-CPS-CONCERT) with write permission. So this should be now solved
